name: personal_expenses
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  intl: ^0.16.1
  sqflite: ^1.3.0
  path: ^1.7.0
  path_provider: ^1.6.24
  flutter_datetime_picker: ^1.4.0
  provider: ^4.3.2+3
  fluttertoast: ^7.1.6
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.6
  firebase_core: ^0.6.0
  firebase_storage: ^6.0.0
  firebase_auth: ^0.19.0+1
  image_picker: ^0.6.7+17
  shared_preferences: ^0.5.12+4
  flutter_icons: ^1.1.0
  email_validator: ^1.0.6
  awesome_dialog: ^1.3.0
  modal_progress_hud: ^0.1.3
  http: ^0.12.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Fraunces
      fonts:
        - asset: assets/fonts/Fraunces.ttf
        - asset: assets/fonts/Fraunces-italic.ttf
          style: italic
