name: personal_expenses
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  intl:
  sqflite:
  path:
  path_provider:
  flutter_datetime_picker:
  provider:
  fluttertoast:
  flutter_facebook_login:
  google_sign_in:
  firebase_core:
  firebase_storage:
  firebase_auth:
  image_picker:
  shared_preferences:
  flutter_icons:
  email_validator:
  awesome_dialog:
  modal_progress_hud:
  http:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Fraunces
      fonts:
        - asset: assets/fonts/Fraunces.ttf
        - asset: assets/fonts/Fraunces-italic.ttf
          style: italic
